# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3fb87c7d6ab5f5ad9472bb9e7b4c79b9c530628cdb70f5fb6f6fa02c3299b97f5d1bee1a6904d05b77a4129f6bf8ffbc2a2a4e2a2eafeafdea74aee825ddac2

test:
  secret_key_base: 560022b0e534914ee8c89ea74f54e3e684d52188942da3f406a67deb02b6190bf72ece87899670f4182acf80d597c46275904b196922c212f06b9c5b1e11f4f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
